name: minimal_todo_journal
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1 #state management
  equatable: ^2.0.8 #comparing objects
  get_it: ^9.2.1 #service locator
  intl: ^0.20.2 #locale
  floor: ^1.5.0 #local database using sqlite
  retrofit: ^4.9.2
  dio: ^5.9.2 #http client used by retrofit
  flutter_hooks: ^0.21.3+1
  cached_network_image: ^3.4.1
  sqflite: ^2.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.4.13
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lora-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lora-BoldItalic.ttf
          weight: 700
          style: italic
